# Generated by Django 3.2.25 on 2025-01-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
    ]
