# Generated by Django 3.2.25 on 2025-01-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
