# Generated by Django 3.2.25 on 2025-01-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('areacode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('post', models.IntegerField()),
                ('city', models.IntegerField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
