# Generated by Django 3.2.25 on 2025-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('AdmissionNumber', models.IntegerField(blank=True, null=True)),
                ('Password1', models.CharField(blank=True, max_length=50, null=True)),
                ('Password2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
